#include<stdio.h>
#defineCOMPARE(x,y)(x<y)?-1:(x==y)?0:1
typedefstruct
{
intexp;
floatcoeff;
}element;
elementterms[100];
intavail=0;
voidattach(floatf,inte)
{
terms[avail].coeff=f;
terms[avail].exp=e;
avail++;
}
voidpolyadd(intstartA,intstartB,intfinishA,intfinishB,int*startD,int*finishD)
{
*startD=avail;
floatsum;
while(startA<finishA&&startB<finishB)
{
switch(COMPARE(terms[startA].exp,terms[startB].exp))
{
case-1:
attach(terms[startB].coeff,terms[startB].exp);
startB++;
break;
case0:
sum=terms[startA].coeff+terms[startB].coeff;
if(sum)
attach(sum,terms[startA].exp);
startA++;
startB++;
break;
case1:
attach(terms[startA].coeff,terms[startA].exp);
startA++;
}
}
while(startA<finishA)
{
attach(terms[startA].coeff,terms[startA].exp);
startA++;
}
for(;startB<finishB;startB++)
attach(terms[startB].coeff,terms[startB].exp);
*finishD=avail;
}
voiddisplay(intstart,intfinish)
{
inti;
for(i=start;i<finish;i++)
printf("%.fx^%d+",terms[i].coeff,terms[i].exp);

printf("\b\n");
}
voidmain()
{
inte,choice,m,n,i,sd,fd;
floatcoeff;
printf("EnterthenumberoftermsinpolyA:");
scanf("%d",&m);
printf("Enterthecoeffandexp\n");
for(i=0;i<m;i++)
{
scanf("%f%d",&coeff,&e);
attach(coeff,e);
}
printf("EnterthenumberoftermsinpolyB:");
scanf("%d",&n);
printf("Enterthecoeffandexp\n");
for(i=0;i<n;i++)
{
scanf("%f%d",&coeff,&e);
attach(coeff,e);
}
polyadd(0,m,m,m+n,&sd,&fd);
printf("PolyA");
display(0,m);
printf("PolyB:");
display(m,m+n);
printf("Resultant:");
display(sd,fd);
}
