#include<stdio.h>
typedefstruct
{
introw;
intcol;
intval;
}terms;
voidfast_transpose(termsu[],termsv[])
{
v[0].row=u[0].row;
v[0].col=u[0].col;
v[0].val=u[0].val;
intnumterms=u[0].val,startingpos[10],rowterms[10];
inti,j;
for(i=0;i<u[0].col;i++)
rowterms[i]=0;
for(i=1;i<=numterms;i++)
rowterms[u[i].col]++;
startingpos[0]=1;
for(i=1;i<u[0].col;i++)
startingpos[i]=startingpos[i-1]+rowterms[i-1];
for(i=1;i<=numterms;i++)
{
j=startingpos[u[i].col]++;
v[j].row=u[i].col;
v[j].col=u[i].row;
v[j].val=u[i].val;
}

}
voiddisplay(termsu[])
{
inti;
printf("Rows\tCols\tVal\n");
for(i=0;i<=u[0].val;i++)
printf("%d\t%d\t%d\n",u[i].row,u[i].col,u[i].val);
}
voidmain()
{
intm,n,i,j,k=1,a[10][10];
termsu[10],v[10];
printf("EnterthenumberofrowsandcolsofmatA:");
scanf("%d%d",&m,&n);
u[0].row=m;
u[0].col=n;
printf("Entertheelements\n");
for(i=0;i<m;i++)
for(j=0;j<n;j++)
{
scanf("%d",&a[i][j]);
if(a[i][j])
{
u[k].row=i;
u[k].col=j;
u[k].val=a[i][j];
k++;
}

}
u[0].val=k-1;
fast_transpose(u,v);
display(u);
printf("\n");
display(v);
}
