#include<stdio.h>
#include<stdlib.h>
intcapacity= 5;
typedefstruct{
intkey;
}element;
element*queue;
intrear=0;
intfront=0;
elementqueueEmpty()
{
elemente;
e.key=-999;
printf("Queueisempty\n");
returne;
}
voidcopy(element*start,element*end,element*q)
{
element*i;
element*j;
i=start;
j=q;
for(i=start;i<end;i++,j++)
*j=*i;
}
voidqueueFull()
{
element*newqueue=(element*)malloc(sizeof(*newqueue)*capacity*2);
intstart=(front+1)%capacity;
if(start<2)
copy(queue+start,queue+start+capacity-1,newqueue);
else{
copy(queue+start,queue+capacity,newqueue);
copy(queue,queue+rear+1,newqueue+capacity-start);
}
front=2*capacity-1;
rear=capacity-2;
capacity=capacity*2;
free(queue);
queue=newqueue;
}
voidaddq(elementitem)
{
rear=(rear+1)%capacity;
if(rear==front)
{
queueFull();
rear=rear+1;
}
queue[rear]=item;
}
elementdeleteq()
{
if(front==rear)
returnqueueEmpty();
front=(front+1)%capacity;

returnqueue[front];
}
voiddisplay(){
if(front==rear)
queueEmpty();
else{
inti;
for(i=(front+1)%capacity;i!=rear;i=(i+1)%capacity)
printf("%d",queue[i].key);
printf("%d",queue[rear].key);
printf("\n");
}
}
intmain()
{
queue=(element*)malloc(sizeof(*queue)*capacity);
intn;
elementitem;
while(1)
{
printf("1.Addq\n2.Delq\n3.Display\n");
scanf("%d",&n);
switch(n)
{
case1:
printf("Entertheelementtoadd:");
scanf("%d",&item.key);
addq(item);
break;
case2:
item=deleteq();
if(item.key!=-999)
printf("Elementdeletedis%d\n",item.key);
break;
case3:
display();
break;
default:
exit(0);
}
}
}
