#include<stdio.h>
typedefenum{lparen,rparen,plus,minus,times,divide,mod,eos,operand}precedence;
precedencestack[100];
inttop=-1;
charexpr[100];
voidpush(precedencetoken)
{
stack[++top]=token;
}
precedencepop()
{
returnstack[top--];
}
precedenceget_token(char*symbol,int*n)
{
*symbol=expr[(*n)++];
switch(*symbol)
{
case'(':returnlparen;
case')':returnrparen;
case'+':returnplus;
case'-':returnminus;
case'*':returntimes;
case'/':returndivide;
case'%':returnmod;
case'\0':returneos;
default:returnoperand;
}

}
voidprint_token(precedencetoken)
{
switch(token)
{
caseplus:printf("+");break;
caseminus:printf("-");break;
casetimes:printf("*");break;
casedivide:printf("/");break;
}
}
intisp[]={0,19,12,12,13,13,13,0};
inticp[]={20,19,12,12,13,13,13,0};
voidmain()
{
intn=0;
charsymbol;
precedencetoken;
push(eos);
printf("Entertheinfixexpression:");
scanf("%s",expr);
for(token=get_token(&symbol,&n);token!=eos;token=get_token(&symbol,&n))
{
if(token==operand)
printf("%c",symbol);
elseif(token==rparen)
{
while(stack[top]!=lparen)

print_token(pop());
pop();
}
else
{
while(isp[stack[top]]>=icp[token])
print_token(pop());
push(token);
}
}
while((token=pop())!=eos)
print_token(token);
pop();
printf("\n");
}
