#include<stdio.h>
#include<stdlib.h>
typedefstruct
{
intkey;
}element;
typedefstructnode
{
elementdata;
structnode*link;
}*queuepointer;
queuepointerfront[10];
queuepointerrear[10];
elementqueueEmpty()
{
elementitem;
item.key=-999;
printf("Thequeueisempty\n");
returnitem;
}
voidaddq(inti,elementitem)
{
queuepointertemp=(queuepointer)malloc(sizeof(*temp));
temp->data=item;
temp->link=NULL;
if(!front[i])
front[i]=temp;
else
rear[i]->link=temp;
rear[i]=temp;
}
elementdeleteq(inti)
{
queuepointertemp=front[i];
if(front[i]==NULL)
returnqueueEmpty();
elementitem=temp->data;
front[i]=front[i]->link;
free(temp);
returnitem;
}
voiddisplay(inti)
{
queuepointertemp=front[i];
if(front[i]==NULL)
queueEmpty();
else
{
for(;temp;temp=temp->link)
printf("%d",temp->data.key);
printf("\n");
}
}
voidmain()
{
intchoice,i,n;

printf("Enterthenumberofqueues:");
scanf("%d",&n);
for(i=0;i<n;i++)
front[i]=rear[i]=NULL;
elementitem;
while(1)
{
printf("1.Addq\n2.Deleteq\n3.Display\n");
scanf("%d",&choice);
switch(choice)
{
case1:
printf("Enterthequeuenoelementtoaddintothequeue:");
scanf("%d%d",&i,&item.key);
addq(i,item);
break;
case2:
printf("Enterthequeuenotodelete:");
scanf("%d",&i);
item=deleteq(i);
if(item.key!=-999)
printf("Theelementdeletedis%d\n",item.key);
break;
case3:
printf("Enterthequeuenotodisplay:");
scanf("%d",&i);
display(i);
break;
default:
exit(0);
}
}
}
