#include<stdio.h>
#include<stdlib.h>
#defineCOMPARE(x,y)(x<y)?-1:(x==y)?0:1
#defineTRUE1
#defineFALSE0
typedefstructnode
{
intexp;
floatcoeff;
structnode*link;
}*polypointer;
voidattach(floatf,inte,polypointer*last)
{
polypointertemp=(polypointer)malloc(sizeof(*temp));
temp->coeff=f;
temp->exp=e;
(*last)->link=temp;
*last=temp;
}
polypointerpolyadd(polypointera,polypointerb)
{
polypointerc,lastC,startA;
intdone=FALSE;
floatsum;
startA=a;
c=(polypointer)malloc(sizeof(*c));
c->exp=-1;
lastC=c;
a=a->link;
b=b->link;
do
{
switch(COMPARE(a->exp,b->exp))
{
case-1:
attach(b->coeff,b->exp,&lastC);
b=b->link;
break;
case0:
if(startA==a)
done=TRUE;
else
{
sum=a->coeff+b->coeff;
if(sum)
attach(sum,a->exp,&lastC);
a=a->link;
b=b->link;
}
break;
case1:
attach(a->coeff,a->exp,&lastC);
a=a->link;
}
}while(!done);
lastC->link=c;

returnc;
}
voiddisplay(polypointera)
{
polypointertemp=a->link;
while(temp!=a)
{
printf("%.fx^%d+",temp->coeff,temp->exp);
temp=temp->link;
}
printf("\b\n");
}
voidmain()
{
intm,n,e,i;
floatf;
polypointera,lastA,b,lastB,c;
a=(polypointer)malloc(sizeof(*a));
lastA=a;
b=(polypointer)malloc(sizeof(*b));
lastB=b;
a->exp=b->exp=-1;
printf("EnterthenumberoftermsinpolyA:");
scanf("%d",&m);
printf("Enterthecoeffandexpofthepoly\n");
for(i=0;i<m;i++)
{
scanf("%f%d",&f,&e);
attach(f,e,&lastA);
}
lastA->link=a;
printf("EnterthenumberoftermsinpolyB:");
scanf("%d",&n);
printf("Enterthecoeffandexp\n");
for(i=0;i<n;i++)
{
scanf("%f%d",&f,&e);
attach(f,e,&lastB);
}
lastB->link=b;
c=polyadd(a,b);
display(a);
display(b);
display(c);
}
